name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Permite executar manualmente

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Cypress E2E Tests
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        headless: true
        record: false
        config-file: cypress.config.js
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 120
        
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots/
        if-no-files-found: ignore
        
    - name: Upload videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos/
        if-no-files-found: ignore
        
    - name: Generate test report
      if: always()
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "**Test Suite**: Cypress E2E Tests" >> $GITHUB_STEP_SUMMARY
        echo "**Date**: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "**Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ **Status**: All tests passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Status**: Some tests failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test Files Executed:" >> $GITHUB_STEP_SUMMARY
        echo "- 01-loading.cy.js" >> $GITHUB_STEP_SUMMARY
        echo "- 02-kanban-structure.cy.js" >> $GITHUB_STEP_SUMMARY
        echo "- 03-functionality.cy.js" >> $GITHUB_STEP_SUMMARY
        echo "- 04-ui-ux.cy.js" >> $GITHUB_STEP_SUMMARY
        echo "- 05-accessibility.cy.js" >> $GITHUB_STEP_SUMMARY
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Artifacts:" >> $GITHUB_STEP_SUMMARY
        echo "- Screenshots (if tests failed)" >> $GITHUB_STEP_SUMMARY
        echo "- Videos (always generated)" >> $GITHUB_STEP_SUMMARY
        
    - name: Create detailed log file
      if: always()
      run: |
        cat > test-execution-log.md << 'EOF'
        # Test Execution Log
        
        ## Test Information
        - **Date**: $(date)
        - **Branch**: ${{ github.ref_name }}
        - **Commit**: ${{ github.sha }}
        - **Runner**: ${{ runner.os }}
        - **Node Version**: $(node --version)
        - **NPM Version**: $(npm --version)
        
        ## Test Results
        - **Status**: ${{ job.status }}
        - **Duration**: ${{ steps.cypress-run.outputs.duration }}
        
        ## Test Files
        1. **01-loading.cy.js** - Testes de carregamento da página
        2. **02-kanban-structure.cy.js** - Verificação da estrutura do Kanban
        3. **03-functionality.cy.js** - Testes das funcionalidades principais
        4. **04-ui-ux.cy.js** - Validação de UI/UX e design
        5. **05-accessibility.cy.js** - Testes de acessibilidade
        
        ## Environment
        - **Site Tested**: https://kanban-dusky-five.vercel.app/
        - **Browser**: Chrome (headless)
        - **Cypress Version**: $(npx cypress --version)
        
        ## Artifacts Generated
        - Screenshots: Available if tests failed
        - Videos: Available for all test runs
        
        ## Notes
        - Tests are executed against the live site
        - All artifacts are uploaded to GitHub Actions
        - Detailed logs available in the Actions tab
        EOF
        
    - name: Upload test log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-execution-log
        path: test-execution-log.md
        if-no-files-found: ignore 